[package]
name = "cuneus"
version = "0.1.2"
edition = "2021"
authors = ["altunenes"]
license = "MIT"
repository = "https://github.com/altunenes/cuneus"
readme = "readme.md"
keywords = ["graphics", "wgpu", "shaders", "gpu"]
categories = ["graphics", "rendering", "shaders"]

[dependencies]
wgpu = "23.0.1"
winit = "0.30.7"
bytemuck = { version = "1.21", features = ["derive"] }
egui-wgpu = "0.30.0"
egui = "0.30.0"
egui-winit = "0.30.0"
image = { version = "0.25.5", features = ["png"] }
env_logger = "0.11.6"
pollster = "0.4.0"
rfd = "0.15.1"
notify = "7.0.0"