name: Shader Binary Release

on:
  push:
    tags:
      - 'v*'

permissions: write-all

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            ext: ""
          - os: windows-latest
            target: x86_64-pc-windows-gnu
            ext: ".exe"
          - os: macos-latest
            target: x86_64-apple-darwin
            ext: ""

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      # Install required dependencies for Linux
      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libudev-dev

      # Build the binary
      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --bin droste

      # Create release directory structure
      - name: Prepare release package
        run: |
          mkdir -p release/droste/shaders
          # Copy the binary
          cp "target/release/droste${{ matrix.ext }}" "release/droste/"
          # Copy shader files
          cp shaders/droste.wgsl release/droste/shaders/
          cp shaders/vertex.wgsl release/droste/shaders/
        shell: bash

      # Create ZIP archive
      - name: Create ZIP archive
        run: |
          cd release
          if [ "${{ runner.os }}" = "Windows" ]; then
            7z a "../droste-${{ matrix.os }}.zip" droste
          else
            zip -r "../droste-${{ matrix.os }}.zip" droste
          fi
        shell: bash

      # Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: droste-${{ matrix.os }}
          path: droste-${{ matrix.os }}.zip

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
